#!/bin/sh

# -------------------------------------------------------
# Terraform Wrapper (terraformw)
# 
# Defines the terraform paramiters before calling it
# -------------------------------------------------------



# --== Jenkins ==-- #
export TF_VAR_jenkins_docker_socket=/var/run/docker.sock
export TF_VAR_jenkins_docker_cli_version=5:24.0.7-1~debian.12~bookworm

terraform "$@"
