#!/bin/sh

# -------------------------------------------------------
# Terraform Wrapper (terraformw)
# 
# Defines the terraform paramiters before calling it
# -------------------------------------------------------


# --== General ==-- #
export TF_VAR_install_root=
export TF_VAR_timezone=
export TF_VAR_hostname=

# --== MySQL ==-- #
export TF_VAR_mysql_root_password=

# --== Keycloak ==-- #
export TF_VAR_keycloak_admin_username=
export TF_VAR_keycloak_admin_password=
export TF_VAR_keycloak_db_username=
export TF_VAR_keycloak_db_password=

# --== Mvn ==-- #
export TF_VAR_mvn_db_username=
export TF_VAR_mvn_db_password=

# --== Jenkins ==-- #
export TF_VAR_jenkins_docker_socket=
export TF_VAR_jenkins_docker_cli_version=

terraform "$@"
